pkg load control;

ventanaPrincipal = figure;
set (ventanaPrincipal,"name","ASIC - Análisis de Sistemas de Control");
set (ventanaPrincipal,"numbertitle","off");
set (ventanaPrincipal,"color",[.5,.5,.5]);
set (ventanaPrincipal,"menubar","none");

entornoPrincipal = uibuttongroup (ventanaPrincipal, "position", [ 0 0 1 1], ...
               "title","Elija su forma de ingresar la función de transferencia", ...
               "titleposition","centertop","fontsize",11,"fontname","Arial");
           
botonCoeficientes = uicontrol (entornoPrincipal,"string","Coeficientes", ...
               "position",[125,250,300,100],"callback",{@abrirVentanaCoeficientes,ventanaPrincipal}, ...
               "backgroundcolor",[.8,.8,.8]);
botonPCG = uicontrol (entornoPrincipal,"string","Polos, ceros y ganancia", ...
               "position",[125,100,300,100],"callback",{@abrirVentanaPCG,ventanaPrincipal}, ...
               "backgroundcolor",[.8,.8,.8]);

function abrirVentanaCoeficientes (handlesource,event,idVentana)
  close (idVentana,"force");
  ventanaCoeficientes = figure;
  set (ventanaCoeficientes,"name","Función de transferencia: Coeficientes");
  set (ventanaCoeficientes,"numbertitle","off");
  
  entornoCoeficientes = uibuttongroup (ventanaCoeficientes, "position", [ 0 0 1 1], ...
               "title","Establezca los coeficientes y elija su opción","titleposition","centertop");
               
  textoCoeficientesNumerador = uicontrol (entornoCoeficientes,"style","text", ...
               "string","Coeficientes del numerador:","position",[10,350,300,40], ... 
               "fontsize",16);  
  coeficientesNumerador = uicontrol (entornoCoeficientes, "style", "edit", ...
               "string", "2,7,4,3", "position",[20,310,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);              
  textoCoeficientesDenominador = uicontrol (entornoCoeficientes,"style","text", ...
               "string","Coeficientes del denominador:","position",[10,250,300,40], ... 
               "fontsize",16);  
  coeficientesDenominador = uicontrol (entornoCoeficientes, "style", "edit", ...
               "string", "6,1,9", "position",[20,210,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);
  botonExpresion = uicontrol (entornoCoeficientes,"string","Expresión", ...
               "position",[390,350,150,30],"callback","mostrarExpresion", ...
               "backgroundcolor",[.8,.8,.8]);
  botonPolos = uicontrol (entornoCoeficientes,"string","Polos", ...
               "position",[390,300,150,30],"callback","mostrarPolos", ...
               "backgroundcolor",[.8,.8,.8]);
  botonCeros = uicontrol (entornoCoeficientes,"string","Ceros", ...
               "position",[390,250,150,30],"callback","mostrarCeros", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGanancia = uicontrol (entornoCoeficientes,"string","Ganancia", ...
               "position",[390,200,150,30],"callback","mostrarGanancia", ...
               "backgroundcolor",[.8,.8,.8]);
  botonExpresionPCG = uicontrol (entornoCoeficientes,"string","Expresión P-C-G", ...
               "position",[390,150,150,30],"callback","mostrarExpresionPCG", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGraficar = uicontrol (entornoCoeficientes,"string","Graficar polos y ceros", ...
               "position",[390,100,150,30],"callback","mostrarGrafico", ...
               "backgroundcolor",[.8,.8,.8]);
  botonEstabilidad = uicontrol (entornoCoeficientes,"string","Indicar estabilidad", ...
               "position",[390,50,150,30],"callback","mostrarEstabilidad", ...
               "backgroundcolor",[.8,.8,.8]);
  botonTodo = uicontrol (entornoCoeficientes,"string","Analizar todo", ...
               "position",[60,80,200,50],"callback","mostrarTodo", ...
               "backgroundcolor",[.2,.8,.2],"fontsize",16);
endfunction

function abrirVentanaPCG (handlesource,event,idVentana)
  close (idVentana,"force");
  ventanaPCG = figure;
  set (ventanaPCG,"name","EN CONSTRUCCIÓN :D");
  set (ventanaPCG,"numbertitle","off");
endfunction
 
function mostrarExpresion (handlesource,event)
endfunction

function mostrarPolos (handlesource,event)
endfunction

function mostrarCeros (handlesource,event)
endfunction

function mostrarGanancia (handlesource,event)
endfunction

function mostrarExpresionPCG (handlesource,event)
endfunction

function mostrarGrafico (handlesource,event)
  g = figure;
  x = -10:0.1:10;
  plot (x, sin (x));
  xlabel ("x");
  ylabel ("sin (x)");
  title ("Rico title papu");
endfunction

function mostrarEstabilidad (handlesource,event)
endfunction

function mostrarTodo (handlesource,event)
endfunction