pkg load control;

function abrirVentanaPrincipal ()
  ventanaPrincipal = figure;
  set (ventanaPrincipal,"name","ASIC - Análisis de Sistemas de Control");
  set (ventanaPrincipal,"numbertitle","off");
  set (ventanaPrincipal,"color",[.5,.5,.5]);
  set (ventanaPrincipal,"menubar","none");

  entornoPrincipal = uibuttongroup (ventanaPrincipal, "position", [ 0 0 1 1], ...
                 "title","Elija su forma de ingresar la función de transferencia", ...
                 "titleposition","centertop","fontsize",11,"fontname","Arial");
             
  botonCoeficientes = uicontrol (entornoPrincipal,"string","Coeficientes", ...
                 "position",[125,250,300,100],"callback",{@abrirVentanaCoeficientes,ventanaPrincipal}, ...
                 "backgroundcolor",[.8,.8,.8]);
  botonPCG = uicontrol (entornoPrincipal,"string","Ceros, polos y ganancia", ...
                 "position",[125,100,300,100],"callback",{@abrirVentanaCPG,ventanaPrincipal}, ...
                 "backgroundcolor",[.8,.8,.8]);
endfunction

function abrirVentanaCoeficientes (handlesource,event,idVentana)
  close (idVentana,"force");
  ventanaCoeficientes = figure;
  set (ventanaCoeficientes,"name","Función de transferencia: Coeficientes");
  set (ventanaCoeficientes,"numbertitle","off");
  
  entornoCoeficientes = uibuttongroup (ventanaCoeficientes, "position", [ 0 0 1 1], ...
               "title","Establezca los coeficientes y elija su opción","titleposition","centertop");
               
  textoCoeficientesNumerador = uicontrol (entornoCoeficientes,"style","text", ...
               "string","Coeficientes del numerador:","position",[10,350,300,40], ... 
               "fontsize",16);  
  coeficientesNumerador = uicontrol (entornoCoeficientes, "style", "edit", ...
               "string", "2,7,4,3", "position",[20,310,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);              
               
  textoCoeficientesDenominador = uicontrol (entornoCoeficientes,"style","text", ...
               "string","Coeficientes del denominador:","position",[10,250,300,40], ... 
               "fontsize",16);  
  coeficientesDenominador = uicontrol (entornoCoeficientes, "style", "edit", ...
               "string", "6,1,9", "position",[20,210,290,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);
               
  botonExpresion = uicontrol (entornoCoeficientes,"string","Expresión", ...
               "position",[390,350,150,30],"callback","mostrarExpresion", ...
               "backgroundcolor",[.8,.8,.8]);
  botonPolos = uicontrol (entornoCoeficientes,"string","Polos", ...
               "position",[390,300,150,30],"callback","mostrarPolos", ...
               "backgroundcolor",[.8,.8,.8]);
  botonCeros = uicontrol (entornoCoeficientes,"string","Ceros", ...
               "position",[390,250,150,30],"callback","mostrarCeros", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGanancia = uicontrol (entornoCoeficientes,"string","Ganancia", ...
               "position",[390,200,150,30],"callback","mostrarGanancia", ...
               "backgroundcolor",[.8,.8,.8]);
  botonExpresionCPG = uicontrol (entornoCoeficientes,"string","Expresión C-P-G", ...
               "position",[390,150,150,30],"callback","mostrarExpresionCPG", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGraficar = uicontrol (entornoCoeficientes,"string","Graficar ceros y polos", ...
               "position",[390,100,150,30],"callback","mostrarGrafico", ...
               "backgroundcolor",[.8,.8,.8]);
  botonEstabilidad = uicontrol (entornoCoeficientes,"string","Indicar estabilidad", ...
               "position",[390,50,150,30],"callback","mostrarEstabilidad", ...
               "backgroundcolor",[.8,.8,.8]);
  botonTodo = uicontrol (entornoCoeficientes,"string","Analizar todo", ...
               "position",[60,80,200,50],"callback","mostrarTodo", ...
               "backgroundcolor",[.2,.8,.2],"fontsize",16);
endfunction

function abrirVentanaCPG (handlesource,event,idVentana)
  close (idVentana,"force");
  ventanaCPG = figure;
  set (ventanaCPG,"name","Función de transferencia: Ceros, polos y ganancia");
  set (ventanaCPG,"numbertitle","off");
  
  entornoCPG = uibuttongroup (ventanaCPG, "position", [ 0 0 1 1], ...
               "title","Establezca los ceros, polos y ganancia y elija su opción", ...
               "titleposition","centertop");
               
  textoCeros = uicontrol (entornoCPG,"style","text", ...
               "string","Ceros:","position",[40,320,80,40], ... 
               "fontsize",16);  
  ceros = uicontrol (entornoCPG, "style", "edit", ...
               "string", "1,1,3,4", "position",[150,320,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);        
               
  textoPolos = uicontrol (entornoCPG,"style","text", ...
               "string","Polos:","position",[40,250,80,40], ... 
               "fontsize",16);  
  polos = uicontrol (entornoCPG, "style", "edit", ...
               "string", "3,4,5", "position",[150,250,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);  
               
  textoGanancia = uicontrol (entornoCPG,"style","text", ...
               "string","Ganancia:","position",[40,180,100,40], ... 
               "fontsize",16);  
  ganancia = uicontrol (entornoCPG, "style", "edit", ...
               "string", "5", "position",[150,180,200,40], ...
               "fontsize",14,"backgroundcolor",[.5,.5,.5]);  
               
  botonExpresion = uicontrol (entornoCPG,"string","Expresión", ...
               "position",[390,350,150,30],"callback","mostrarExpresion", ...
               "backgroundcolor",[.8,.8,.8]);
  botonPolos = uicontrol (entornoCPG,"string","Polos", ...
               "position",[390,300,150,30],"callback","mostrarPolos", ...
               "backgroundcolor",[.8,.8,.8]);
  botonCeros = uicontrol (entornoCPG,"string","Ceros", ...
               "position",[390,250,150,30],"callback","mostrarCeros", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGanancia = uicontrol (entornoCPG,"string","Ganancia", ...
               "position",[390,200,150,30],"callback","mostrarGanancia", ...
               "backgroundcolor",[.8,.8,.8]);
  botonExpresionCPG = uicontrol (entornoCPG,"string","Expresión C-P-G", ...
               "position",[390,150,150,30],"callback","mostrarExpresionCPG", ...
               "backgroundcolor",[.8,.8,.8]);
  botonGraficar = uicontrol (entornoCPG,"string","Graficar ceros y polos", ...
               "position",[390,100,150,30],"callback","mostrarGrafico", ...
               "backgroundcolor",[.8,.8,.8]);
  botonEstabilidad = uicontrol (entornoCPG,"string","Indicar estabilidad", ...
               "position",[390,50,150,30],"callback","mostrarEstabilidad", ...
               "backgroundcolor",[.8,.8,.8]);
  botonTodo = uicontrol (entornoCPG,"string","Analizar todo", ...
               "position",[60,80,200,50],"callback","mostrarTodo", ...
               "backgroundcolor",[.2,.8,.2],"fontsize",16);
endfunction
 
function mostrarExpresion (handlesource,event)
endfunction

function mostrarPolos (handlesource,event)
endfunction

function mostrarCeros (handlesource,event)
endfunction

function mostrarGanancia (handlesource,event)
endfunction

function mostrarExpresionCPG (handlesource,event)
endfunction

function mostrarGrafico (handlesource,event)
  g = figure;
  x = -10:0.1:10;
  plot (x, sin (x));
  xlabel ("x");
  ylabel ("sin (x)");
  title ("Rico title papu");
endfunction

function mostrarEstabilidad (handlesource,event)
endfunction

function mostrarTodo (handlesource,event)
endfunction

abrirVentanaPrincipal();